<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <OutputType>WinExe</OutputType>
	  <TargetFramework>net6.0-windows</TargetFramework>
	  <LangVersion>latest</LangVersion>
	  <Nullable>enable</Nullable>
	  <UseWindowsForms>true</UseWindowsForms>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <StartupObject>WinFormsNET6.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\WinFormsSampleNet472\R3Extends4WinFormsSample.cs" Link="R3Extends4WinFormsSample.cs" />
    <Compile Include="..\WinFormsSampleNet472\R3Extends4WinFormsSample.Designer.cs" Link="R3Extends4WinFormsSample.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.0" />
    <PackageReference Include="PolySharp" Version="1.15.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="R3" Version="1.3.0" />
    <PackageReference Include="R3Extends4WinForms" Version="0.2.0" />
    <PackageReference Include="R3Extensions.WinForms" Version="1.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SampleCommonModules\SampleCommonModules.csproj" />
  </ItemGroup>

</Project>