<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<TargetFrameworks>net472;net8.0-windows</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<AssemblyVersion>0.1.0.0</AssemblyVersion>
		<FileVersion>0.1.0.0</FileVersion>
		<Description>R3's observable object from WinForms event.</Description>
		<Copyright></Copyright>
		<PackageProjectUrl>https://github.com/w-red/R3Extends4WinForms</PackageProjectUrl>
		<RepositoryUrl>https://github.com/w-red/R3Extends4WinForms</RepositoryUrl>
		<PackageTags>R3; Windows Form; WinForms;</PackageTags>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>R3Extends4WinForms</Title>
		<Authors>TERASHI, yohei</Authors>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Version>0.1.0.0</Version>
		<PackageReleaseNotes>Initial Preview.</PackageReleaseNotes>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

    <ItemGroup>
		<None Include="..\README.md">
		    <Pack>True</Pack>
		    <PackagePath>\</PackagePath>
	    </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="R3" Version="1.3.0" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
          <DesignTime>True</DesignTime>
          <AutoGen>True</AutoGen>
          <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
        <Compile Update="Properties\Settings.Designer.cs">
            <DesignTimeSharedInput>True</DesignTimeSharedInput>
            <AutoGen>True</AutoGen>
            <DependentUpon>Settings.settings</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Properties\Resources.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <None Update="Properties\Settings.settings">
            <Generator>SettingsSingleFileGenerator</Generator>
            <LastGenOutput>Settings.Designer.cs</LastGenOutput>
        </None>
        <None Update="README.md">
            <Pack>True</Pack>
            <PackagePath>\</PackagePath>
        </None>
    </ItemGroup>

</Project>
